apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress-kubernetes-ingress
  namespace: haproxy-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
    appProtocol: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
    appProtocol: https
  - name: stat
    port: 1024
    protocol: TCP
    targetPort: stat
  - name: admin
    port: 6060
    protocol: TCP
    targetPort: admin
